
analyzer:
  errors:
    no_leading_underscores_for_local_identifiers: ignore
include: package:lints/recommended.yaml

linter:
  rules:
    non_constant_identifier_names: false
    unnecessary_this: false

