name: meiyou_extensions
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.2
  okhttp:
    git:
      url: https://github.com/Noobware1/okhttp.git
      ref: master
  crypto_dart:
    git:
      url: https://github.com/Noobware1/crypto_dart.git
      ref: master
  meiyou_extensions_lib:
    git:
      url: https://github.com/Noobware1/meiyou_extensions_lib.git
      ref: master
  dart_eval:
    git:
      url: https://github.com/Noobware1/dart_eval.git
      ref: fixes
  archive:
  html: ^0.15.4
  intl: ^0.19.0
  isar: 3.1.0+1
  # analyzer: ^6.4.1
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
