name: meiyou_extensions_repo
description: Repository containing all the plugins availble for Meiyou app.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  meiyou_extensions_lib:
    git:
      url: https://github.com/Noobware1/meiyou_extensions_lib.git
      ref: master
  archive:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
