name: yomiroll
sourceName: Yomiroll
description: No description
lang: all
version: 1.0.0
nsfw: 0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  # isar: 3.1.0+1
  okhttp:
    git:
      url: https://github.com/Noobware1/okhttp.git
      ref: master
  crypto_dart:
    git:
      url: https://github.com/Noobware1/crypto_dart.git
      ref: master
  meiyou_extensions_lib:
    git:
      url: https://github.com/Noobware1/meiyou_extensions_lib.git
      ref: master

dev_dependencies:
  lints: ^2.1.0
